# Generated by Django 3.2.5 on 2022-01-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='history_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('resultTime', models.CharField(max_length=255)),
                ('resultText', models.CharField(max_length=255)),
                ('memo', models.CharField(max_length=255)),
            ],
        ),
    ]
