# Generated by Django 3.2.5 on 2022-01-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_history_tbl_create_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_tbl',
            name='mode',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
