# Generated by Django 3.2.5 on 2022-01-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_history_tbl_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_tbl',
            name='resultCharacter',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history_tbl',
            name='resultQuestion',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
