# Generated by Django 3.2.5 on 2021-12-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_name', models.CharField(max_length=255)),
                ('inter_date', models.DateField(default='0000-0000-000')),
                ('inter_time', models.TimeField(blank=True, null=True)),
                ('con_place', models.CharField(blank=True, max_length=255)),
                ('tel_number', models.IntegerField(blank=True, null=True)),
                ('con_address', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(default='#4682b4', max_length=7)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
