# Generated by Django 3.2.5 on 2022-01-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_tbl',
            name='create_user',
            field=models.CharField(default=' ', max_length=150),
            preserve_default=False,
        ),
    ]
